### PR TITLE
WIP #464 fixed first batch of badges specs

### PR DESCRIPTION
**Pull request by nicolasiensen**
Specs that will continue to be skipped:
* ```specs/badges/changelogd_spec```: The ChangeLog API integration is no longer being maintained, the Changelogd spec have some failing tests related to the API integration and this class must be refactored;

### CODE REVIEW

**Comment by seuros** [comment]
Could you rebase and remove the 2 last commit. ?

**Comment by nicolasiensen** [comment]
@seuros it's done, thanks for helping!

**Comment by seuros** [comment]
@nicolasiensen rebase please.

**Comment by nicolasiensen** [comment]
@seuros I'm considering to remove this pull request and start over from the master, there were lot's of changes on the master that reflected on the tests I was fixing. What do you think?

**Comment by seuros** [comment]
:+1:

**Pull request closed without merging**
