### PR TITLE
remove airbrake, add bugsnag

### PR DESCRIPTION
**Pull request by avinoth**
Removed Airbrake gem and its initializer.
Added Bugsnag gem and its initializer.

[Change ENV_VAR to BUGSNAG_API_KEY]

### CODE REVIEW

**Comment by seuros** [comment]
Are you sure there is no Airbrake reference in the codebase ?

**Comment by avinoth** [comment]
Yep.. https://github.com/avinoth/coderwall/search?utf8=%E2%9C%93&q=airbrake

**Comment by rohitpaulk** [comment]
@seuros - How about getting rid of Honeybadger as well? Looks like all the calls are commented out.

**Comment by seuros** [comment]
Yes, @avinoth can you do it please ?

**Comment by avinoth** [comment]
Ok!

**Comment by seuros** [comment]
:heart:

**Pull request merged**
