### PR TITLE
remove existing changeLog'd API integration - Bounty #488

### PR DESCRIPTION
**Pull request by codebender**
[Remove the ChangeLog API integration](https://assembly.com/coderwall/bounties/488)
---
- remove existing api integration
- support existing badges

### CODE REVIEW

**Comment by seuros** [comment]
This caused RuntimeError: NOT IMPLEMENTED 
```
/app/models/badges/badge_base.rb:60 in "award?"
/app/models/badges/badge_base.rb:22 in "block in award!"
/app/models/badges/badge_base.rb:21 in "select"
/app/models/badges/badge_base.rb:21 in "award!"
/app/models/user.rb:447 in "check_achievements!"
/app/jobs/refresh_user_job.rb:14 in "perform"
```

**Comment by rohitpaulk** [comment]
Yes, and it's blocking new signups.

**Comment by seuros** [comment]
reverted!

**Comment by codebender** [comment]
@seuros @rohitpaulk looks like I need to add back the ```award?``` method and return false

**Pull request merged**
